function [names,preds,durs] = ...
    buildIntegrationStream(names,preds,durs,sched,antennaProductionNodes,composite,arrayTest)

[names,preds,durs,finalAssembly] = addTask(names,preds,durs,...
    'Final Assembly Completion',sched('Final Assembly Completion'),...
    [antennaProductionNodes composite arrayTest]);

[names,preds,durs,~] = addTask(names,preds,durs,...
    'Final System Test',sched('Final System Test'),finalAssembly);

end