function compDB = getComponentDB()

% =====================================================
% SPIRAL ANTENNA COMPONENTS
% =====================================================

compDB.spiral_cavity = struct( ...
    'manufacturing','outsourced', ...
    'process','machining', ...
    'tooling_required',false, ...
    'duration_model','hybrid', ...
    'per_unit_time',2, ...
    'vendor_lead_time',30);

compDB.spiral_insert = struct( ...
    'manufacturing','inhouse', ...
    'process','machining', ...
    'tooling_required',false, ...
    'duration_model','linear', ...
    'per_unit_time',0.5, ...
    'vendor_lead_time',0);

% =====================================================
% HORN ANTENNA COMPONENTS
% =====================================================

compDB.horn_body = struct( ...
    'manufacturing','outsourced', ...
    'process','machining', ...
    'tooling_required',false, ...
    'duration_model','hybrid', ...
    'per_unit_time',3, ...
    'vendor_lead_time',40);

% =====================================================
% BICONICAL ANTENNA COMPONENTS
% =====================================================

compDB.biconical_arm = struct( ...
    'manufacturing','outsourced', ...
    'process','machining', ...
    'tooling_required',false, ...
    'duration_model','hybrid', ...
    'per_unit_time',2, ...
    'vendor_lead_time',25);

compDB.bicone_support = struct( ...
    'manufacturing','inhouse', ...
    'process','machining', ...
    'tooling_required',false, ...
    'duration_model','linear', ...
    'per_unit_time',0.8, ...
    'vendor_lead_time',0);

% =====================================================
% CONFORMAL ANTENNA COMPONENTS
% =====================================================

compDB.conformal_patch = struct( ...
    'manufacturing','inhouse', ...
    'process','pcb', ...
    'tooling_required',false, ...
    'duration_model','linear', ...
    'per_unit_time',1.5, ...
    'vendor_lead_time',0);

compDB.conformal_cover = struct( ...
    'manufacturing','procured', ...
    'process','procurement', ...
    'tooling_required',false, ...
    'duration_model','fixed', ...
    'per_unit_time',0, ...
    'vendor_lead_time',12);

% =====================================================
% COMPOSITE STRUCTURES (shared across antennas)
% =====================================================

compDB.composite_shell = struct( ...
    'manufacturing','inhouse', ...
    'process','composite', ...
    'tooling_required',true, ...
    'duration_model','linear', ...
    'per_unit_time',4, ...
    'vendor_lead_time',0);

% =====================================================
% METAL STRUCTURES (shared)
% =====================================================

compDB.base_plate = struct( ...
    'manufacturing','outsourced', ...
    'process','machining', ...
    'tooling_required',false, ...
    'duration_model','hybrid', ...
    'per_unit_time',1.5, ...
    'vendor_lead_time',20);

compDB.mounting_bracket = struct( ...
    'manufacturing','outsourced', ...
    'process','machining', ...
    'tooling_required',false, ...
    'duration_model','hybrid', ...
    'per_unit_time',1, ...
    'vendor_lead_time',20);

% =====================================================
% ELECTRONICS / PCB COMPONENTS
% =====================================================

compDB.pcb_layer = struct( ...
    'manufacturing','outsourced', ...
    'process','pcb', ...
    'tooling_required',false, ...
    'duration_model','fixed', ...
    'per_unit_time',0, ...
    'vendor_lead_time',18);

compDB.rf_connector = struct( ...
    'manufacturing','procured', ...
    'process','procurement', ...
    'tooling_required',false, ...
    'duration_model','fixed', ...
    'per_unit_time',0, ...
    'vendor_lead_time',10);

% =====================================================
% ENCLOSURE / ARRAY STRUCTURE
% =====================================================

compDB.array_enclosure = struct( ...
    'manufacturing','outsourced', ...
    'process','fabrication', ...
    'tooling_required',false, ...
    'duration_model','fixed', ...
    'per_unit_time',0, ...
    'vendor_lead_time',25);

end
